version: '3.9'
services:
  redis:
    container_name: pippin_redis
    image: redis:6-alpine
    restart: unless-stopped
    networks: [ 'app-network' ]

  db:
    container_name: stablecog_go_postgres
    image: postgres:14
    user: 1000:20
    ports:
      - '127.0.0.1:53337:5432'
    restart: unless-stopped
    environment:
      - POSTGRES_DB=stablecog_go
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - PGDATA=/var/lib/postgresql/data/dev
    volumes:
      - .data/postgres:/var/lib/postgresql/data:delegated # Delegated indicates the containers view of the volume takes priority
    networks: [ 'app-network' ]

  app:
    container_name: stablecog_go_dev
    image: appditto/go-vscode-dev:latest
    security_opt:
      - 'seccomp:unconfined'
    environment:
      - GOPRIVATE=github.com/stablecog
      - PORT=13337
      - REDIS_CONNECTION_STRING=redis://redis:6379
    ports:
      - '127.0.0.1:13337:13337'
    volumes:
      - $PWD:/home/go/app
      - $HOME/.gitconfig:/home/go/.gitconfig
      - $HOME/.ssh:/home/go/.ssh
    restart: on-failure
    entrypoint: /bin/zsh
    stdin_open: true
    tty: true
    user: go
    networks: [ 'app-network' ]

networks:
  app-network:
    driver: bridge
