name: 💫 Lambda

on:
  push:
    branches: [master]
    paths: ["lambda/**"]

jobs:
  deploy_lambda:
    name: Deploy lambda
    runs-on: ubuntu-latest
    steps:
      - name: checkout source code
        uses: actions/checkout@v1

      - name: Install Go
        uses: actions/setup-go@v3
        with:
          go-version: "1.20"

      - name: Build binary (QA)
        run: |
          cd lambda && CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -ldflags "-s -w -X main.WebhookUrl=${{ secrets.DISCORD_WEBHOOK_LAMBDA }}" -o lambda && zip deployment.zip lambda && cd ..

      - name: Deploy QA Lambda
        uses: appleboy/lambda-action@master
        with:
          aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws_region: us-east-1
          function_name: QA_Status_Webhook
          zip_file: lambda/deployment.zip

      - name: Build binary (PROD)
        run: |
          cd lambda && CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -ldflags "-s -w -X main.WebhookUrl=${{ secrets.DISCORD_WEBHOOK_LAMBDA_PROD }}" -o lambda && zip deployment_prod.zip lambda && cd ..

      - name: Deploy PROD Lambda
        uses: appleboy/lambda-action@master
        with:
          aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws_region: us-east-1
          function_name: PROD_Status_Webhook
          zip_file: lambda/deployment_prod.zip
