name: GitHub Actions
on: push
jobs:
  deploy:
    runs-on: ubuntu-22.04
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true  
          fetch-depth: 0    

      - name: Get branch name
        id: branch-name
        uses: tj-actions/branch-names@v6

      - uses: benjlevesque/short-sha@v2.1
        if: always()
        id: short-sha
        with:
          length: 8
          
      - id: 'auth'
        name: 'Authenticate to Google Cloud'
        uses: 'google-github-actions/auth@v0'
        with:
          token_format: 'access_token'
          workload_identity_provider: 'projects/744661338714/locations/global/workloadIdentityPools/my-pool/providers/my-provider'
          service_account: 'github-actions-service-account@rox-cloud.iam.gserviceaccount.com'
        
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          registry: gcr.io
          username: oauth2accesstoken
          password: ${{ steps.auth.outputs.access_token }}
          
      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          push: true
          context: .
          tags: |
            gcr.io/rox-cloud/sc-go:latest
            gcr.io/rox-cloud/sc-go:${{ steps.short-sha.outputs.sha }}
