name: GitHub Actions
on: push
jobs:
  deploy:
    runs-on: ubuntu-22.04
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true  
          fetch-depth: 0    

      - name: Get branch name
        id: branch-name
        uses: tj-actions/branch-names@v6

      - uses: benjlevesque/short-sha@v2.1
        if: always()
        id: short-sha
        with:
          length: 8
          
      - id: 'auth'
        name: 'Authenticate to Google Cloud'
        uses: 'google-github-actions/auth@v1'
        with:
          credentials_json: '${{ secrets.GCP_SA_KEY }}'
        
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          registry: gcr.io
          username: _json_key
          password: '${{ secrets.GCP_SA_KEY }}'
          
      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          push: true
          context: .
          tags: |
            gcr.io/synthica/sc-go:latest
            gcr.io/synthica/sc-go:${{ steps.short-sha.outputs.sha }}

      - uses: actions-hub/gcloud@master
        env:
          PROJECT_ID: synthica
          APPLICATION_CREDENTIALS: '${{ secrets.GCP_SA_KEY }}'
        with:
          args: compute instances update-container sc-go-instance --zone us-central1-a --container-image gcr.io/synthica/sc-go:${{ steps.short-sha.outputs.sha }}